# +-----------------------------------------------------
# |         SERVER CONFIG
# +-----------------------------------------------------
server:
  port: 8085
  servlet:
    context-path: /aa
    session:
      cookie:
        name: UISESSION

soap:
  service:
    aa:
      host: ${AA_HOST:localhost}
      port: ${AA_PORT:7070}
      url: http://${soap.service.aa.host}:${soap.service.aa.port}/bookings/ws

logging:
  level:
    org.springframework.web: DEBUG
    co.edu.javeriana: DEBUG