# +-----------------------------------------------------
# |         SERVER CONFIG
# +-----------------------------------------------------
server:
  port: 8088
  servlet:
    context-path: /cc
    session:
      cookie:
        name: UISESSION

soap:
  service:
    cc:
      host: ${AA_HOST:localhost}
      port: ${AA_PORT:8090}
      url: http://${soap.service.cc.host}:${soap.service.cc.port}/ws

logging:
  level:
    org.springframework.web: DEBUG
    co.edu.javeriana: DEBUG